remote_theme: sujaykundu777/devlopr-jekyll  # Don't touch ( required for this theme)

# Edit your preferences below 
title: Angela Hollings
subtitle: Computer Systems Engineering Student
description: >- # this means to ignore newlines until "baseurl:"
  A computer systems engineering student passionate about the intersection of AI and IoT

url: "https://angela.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /about
    - text: Contact Me
      url : /contact

# Edit these details 

author_logo: profile.jpg
author: Angela Hollings
author_bio: A computer systems engineering student passionate about the intersection of AI and IoT 
author_email: "ange.hollings@gmail.com"
author_location: Auckland, New Zealand
author_website_url: "https://angela.github.io"

author_work_experiences: 
            - company_name: Biztalk Toastmasters
              company_logo: Toastmasters.png
              company_url: https://www.facebook.com/BiztalkToastmasters/
              designation: President
              description: Lead a team of 8 to foster a growth culture in our public speaking club of 20+ members
              visibility: true
            - company_name: Robogals
              company_logo: robogals.png
              company_url: https://www.facebook.com/RobogalsAKL/
              designation: Schools Manager
              description: Organised 16+ Robotics workshops for over 300 kids to foster enthusiasm in STEM in young girls
              visibility: true

author_education_details:
              - college_logo: uoa.png
                college_name: The University of Auckland
                college_url: https://www.auckland.ac.nz/en/study/study-options/find-a-study-option/computer-systems-engineering.html
                college_degree: Computer Systems Engineering
                description: Course work includes Object Oriented Programming, Fundamentals of Computer Engineering, Analogue and Digital Design
                visibility: true

author_project_details:
              - project_thumbnail: arduino.png
                project_title: Arduino Programming
                project_description: Programmed 18+ circuits to enchance my electronics programming over the summer
                project_url: bit.do/AngelaC
                visibility: true
              - project_thumbnail: kmeans.jpg
                project_title: K-means Algorithm in MatLab
                project_description: Developed an efficient k-means algorithm from scratch in matlab, taking 4 seconds on average for 5 colours
                project_url: https://github.com/AngelaLH/MatlabProject
                visibility: true

author_writing_details:
              - writing_thumbnail: uoa.png
                writing_title: Part II Student Blog
                writing_description: Created 6 blogs  for 1000+ Part I Engineering Students to study Computer Systems Engineering 
                writing_url: https://www.auckland.ac.nz/en/study/study-options/find-a-study-option/computer-systems-engineering.html
                visibility: true

# social links
github_username:  AngelaLH
linkedin_username: angela-hollings

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-46783401-10 

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true
show_author_writing_details: true

# dont touch this unless required
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme
  # - jekyll-archives

# pagination of posts
paginate: 8
per_page: 4
paginate_path: "/blog/page/:num/"

# minify 
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'


